server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      discovery:
        enabled: true
      server:
        native:
          search-locations:
          - file:///Users/qiu/workspaces/SpringCloudDemo/configserver/src/main/resources/config/licensingservice
          - file:///Users/qiu/workspaces\SpringCloudDemo\configserver\src\main\resources\config\organizationservice
          - file:///Users/qiu/workspaces\SpringCloudDemo\configserver\src\main\resources\config\specialroutesservice
