server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      discovery:
        enabled: true
      server:
        native:
          search-locations:
          - file:///D:\Study/SpringCloudDemo/configserver/src/main/resources/config/licensingservice
          - file:///D:\Study\SpringCloudDemo\configserver\src\main\resources\config\organizationservice
          - file:///D:\Study\SpringCloudDemo\configserver\src\main\resources\config\specialroutesservice
          - file:///D:\Study\SpringCloudDemo\configserver\src\main\resources\config\authenticationservice
          - file:///D:\Study\SpringCloudDemo\configserver\src\main\resources\config\orgservice
          - file:///D:\Study\SpringCloudDemo\configserver\src\main\resources\config\licservice
